DECLARE @TableName VARCHAR(100) = 'Address';

SELECT 
	COLUMN_NAME
	,DATA_TYPE
	,CHARACTER_MAXIMUM_LENGTH
	,NUMERIC_PRECISION
	,NUMERIC_SCALE
	,ORDINAL_POSITION
FROM INFORMATION_SCHEMA.columns
WHERE TABLE_NAME = @TableName
ORDER BY ORDINAL_POSITION